### ISSUE TITLE
每个md文件的头和尾加空行

### ISSUE THREAD

**Issue by gongym12138** [SCLeoX/Wearable-Technology#1]
RT，比较方便合并查看

**Comment by SCLeoX** [comment]
hmmm... 我不是很清楚你想做什么，但是如果你想自行合并所有章节到一个文件的话，你只需要合并完成后全文替换 “#” 为 “\n#” 就好了。

不管怎么样，（棒读）我希望能跟你讲一下我们的炫酷阅读器，[https://scleox.github.io/Wearable-Technology/?chapter=0]()。

**Comment by gongym12138** [comment]
> hmmm... 我不是很清楚你想做什么，但是如果你想自行合并所有章节到一个文件的话，你只需要合并完成后全文替换 “#” 为 “\n#” 就好了。
> 
> 不管怎么样，（棒读）我希望能跟你讲一下我们的炫酷阅读器，https://scleox.github.io/Wearable-Technology/?chapter=0。

了解了，是我蠢了。我是想合并在一起
