### ISSUE TITLE
小小的文本勘误

### ISSUE THREAD

**Issue by mybelovedlz** [SCLeoX/Wearable-Technology#185]
https://wt.tepis.me/#%E4%B8%BB%E7%BA%BF/%E7%AC%AC-14-%E7%AB%A0.html
目测高中生写微积分题目不会用这样的语法
![1](https://user-images.githubusercontent.com/52537886/83892361-24e79d00-a781-11ea-81ec-1767a7261d90.png)

**Comment by ayalhw** [comment]
并不……

**Comment by mybelovedlz** [comment]
@ayalhw 这种 LaTeX/MathJax 式语法并不会直接直接在纸上写，目测是作者没有转义它。

**Comment by SCLeoX** [comment]
> @ayalhw 这种 LaTeX/MathJax 式语法并不会直接直接在纸上写，目测是作者没有转义它。

并不，我只是觉得把 LaTeX 直接写在纸上挺有意思的（

**Comment by mybelovedlz** [comment]
啊这。。。。。。。。

**Comment by ayalhw** [comment]
> 并不，我只是觉得把 LaTeX 直接写在纸上挺有意思的（

+1

**Comment by xtlsoft** [comment]
事实上，高中并没有微积分题目了现在。

**Comment by mybelovedlz** [comment]
我低估了诸位的恶趣味了233
