### ISSUE TITLE
评论区 | 道具集 > 50 - 强制灌食器

### ISSUE THREAD

**Issue by SCLeoX** [SCLeoX/Wearable-Technology#37]

**Comment by dyingsu** [comment]
为什么 琳 的 幻想 老 是 让 咱 似曾相识，就 似乎 完全 符合 自己 的 想法，hmmm，不过 这 可能 是 神经 已经 习惯 了 在 看 之前 就 知道 会 看到 什么 喵？

**Comment by daqieee** [comment]
鲜榨精液，口怕
