### ISSUE TITLE
评论区 | 道具集 > 24 - mWatch

### ISSUE THREAD

**Issue by AobaSeimukei** [SCLeoX/Wearable-Technology#47]

**Comment by SCLeoX** [comment]
这篇棒极了的文章是青叶写哒，大家快去夸她~ @AobaSeimukei

**Comment by ArknightsTexas** [comment]
> 这篇棒极了的文章是青叶写哒，大家快去夸她~ @AobaSeimukei

（夸

**Comment by BobGuoYilong** [comment]
手表需要32g的存储吗

**Comment by lslqtz** [comment]
其实我觉着暂时不需要，然而水果就是这么做了。。我现在才用了 8G 多一些（16G 暂时够了）

**Comment by BobGuoYilong** [comment]
> 其实我觉着暂时不需要，然而水果就是这么做了。。我现在才用了 8G 多一些（16G 暂时够了）

手表能用8G+？
大佬您表里面装了啥啊

**Comment by lslqtz** [comment]
音乐 4G，系统和其它 App 应该也是 4G 左右。。
32G 是多了
