### ISSUE TITLE
评论区 | 道具集 > 79 - 充电宝少女捕获器

### ISSUE THREAD

**Issue by Patika-ailemait** [SCLeoX/Wearable-Technology#54]

**Comment by Patika-ailemait** [comment]
此创意来源自[一个充电宝爆炸的事故](https://zhuanlan.zhihu.com/p/63084885)，由于化名撞上了于是便想写点什么。
耗时一周鸽出了本文。

**Comment by SCLeoX** [comment]
@Patika-ailemait 科幻部分太强了（
