### ISSUE TITLE
评论区 | 道具集 > 150 - 载人风筝

### ISSUE THREAD

**Issue by SCLeoX** [SCLeoX/Wearable-Technology#58]

**Comment by kidv1412** [comment]
配图好评！gj！正文要是能加上配图就好了，一万个脑海中浮现的镜头

**Comment by water-lift** [comment]
> 配图好评！gj！正文要是能加上配图就好了，一万个脑海中浮现的镜头

可是配图不对啊。。。穿了裙子的。。。

**Comment by SCLeoX** [comment]
@water-lift 因为是找人画的，然后画的人不懂中文，所以画出来的东西和实际描述不是很吻合...

**Comment by Frost-cn** [comment]
最后好甜啊！i了i了。
对比来看我的描写好干枯，要好好学习了！
