### ISSUE TITLE
评论区 | 道具集 > 667 - 可穿戴科技的其他版本②

### ISSUE THREAD

**Issue by SCLeoX** [SCLeoX/Wearable-Technology#99]

**Comment by oceandeviant** [comment]
这种轻度的文章读起来也很棒！有个小建议（当然瑕不掩瑜），可以不取消安全词———因为不能使用安全词的情况下容易使“新装置”与主线那种绝对强制的装置相似（一周对新人已经是很长时间了），不是很符合琥珀这种没那么抖m却又想体验贞操带的女生。可以考虑：使用安全词后相当长时间内不能再使用装置（故自慰达不到她已知的最大快感，因而增加安全词的使用代价）；或者更S一点的选项，在约定的时间内（比如文中的一周）使用安全词仅可以使内部装置停止运作（维持排泄，清洗等基本操作），但仍不能解开装置，当然也无法达到高潮，直至主角认为自己已经恢复可以重新将权限交还AI或等待一周后解开装置进行更长时间的恢复（后者有时还不如努力完成AI要求获得奖励，只有真正绝望才会选择吧）。抛砖引玉，静候大家高见。

**Comment by fyxyy** [comment]
我也想变成女孩子，穿戴这个装备

**Comment by h0353914** [comment]
看本篇的時候感覺第一次看到那麼合胃口的小說但是 但是不喜歡黑暗危險的感覺@.@ 這個版本更喜歡 期待續作
